### ISSUE TITLE
Lucid renders all attributes as lowercase

### ISSUE THREAD

**Issue by seanhess** [chrisdone/lucid#100]
I'm experimenting with converting server-side rendered HTML into react components (Don't ask). 

React is very grumpy that some attributes are lowercase instead of camelcase. For example, `defaultValue` and `onChange`. Even if I redefine the attributes using `makeAttribute`, they still come out lowercase. 

Is there a way to have the case of the attribute preserved as specified in `makeAttribute`?

**Comment by seanhess** [comment]
Will do. Also, I am definitely abusing these tools. No need to accept this
as an issue.

Le ven. 30 oct. 2020 à 12:00 PM, Oleg Grenrus <notifications@github.com> a
écrit :

**Comment by chrisdone** [comment]
I was doing something similar, in the end I found it easier to generate React.createElement calls, but ymmv.

**Comment by seanhess** [comment]
Oops, you're right, Lucid does render it correctly. This issue is arising from a different part of this madness. 

You're probably right about generating React.createElement calls. I'm currently using lucid to generate HTML, then HTMLReactParser (https://www.npmjs.com/package/html-react-parser) to convert to react, all so I can get server-side rendered vdom. The camelcase issue matters because I'm supposed to be imitating the output of ReactDOMServer, which serializes react views to html, and is case sensitive. 

I definitely want the server-side code to "think" it's generating html, but it would be better to make a custom renderer. 

Thanks for your help!
