### ISSUE TITLE
Add Lift instance

### ISSUE THREAD

**Issue by turion** [chrisdone/lucid#101]
It would nice to use lucid at compile time to generate HTML. But this is only easily possible if `Html ()` is an instance of [`lift`](http://hackage.haskell.org/package/template-haskell-2.16.0.0/docs/Language-Haskell-TH-Syntax.html#v:lift). ~See also https://hackage.haskell.org/package/th-lift~ See also the `DeriveLift` extension.

**Comment by phadej** [comment]
```haskell
toHtmlRaw $(lift $ renderText html)
```
?

I don't see a reason of lifting `Html ()` itself - there's barely any computation done.

**Comment by turion** [comment]
Yes, that's a good workaround, and also the one I'm currently using. But it requires knowing that `Text` has a `Lift` instance, and that `toHtmlRaw` and `renderText` are inverse. So simply adding `derive Lift` would be cleaner.

**Comment by chrisdone** [comment]
A `deriving Lift` doesn't work. I think you'll need a manual instance. I'd be interested to see what you come up with, and whether it isn't @phadej's definition.

**Comment by phadej** [comment]
There cannot be true `Lift` instance. Recall

```haskell
newtype HtmlT m a =
  HtmlT {runHtmlT :: m (HashMap Text Text -> Builder,a)
```

That (somewhat arbitrary) function is non liftable.

**Comment by turion** [comment]
I see. Then the workaround is probably the best that is currenly possible. Thanks for the explanation!
