### ISSUE TITLE
Render output depends on hashable version

### ISSUE THREAD

**Issue by sjakobi** [chrisdone/lucid#107]
`dhall-docs` has a golden test suite that uses `lucid`. As of https://github.com/dhall-lang/dhall-haskell/commit/5a93d5f70601bb596616df3a583d7d984ec6ea94 the tests pass when `hashable < 1.3.1` is used but fail with `hashable-1.3.1.0` with diffs like

```diff
-<a data-path="/InvalidBlockComment.dhall" class="copy-to-clipboard">
+<a class="copy-to-clipboard" data-path="/InvalidBlockComment.dhall">
```

Since `dhall-docs` doesn't use `hashable` directly, I'm hesitant to pin `hashable` in its testsuite. IMHO, since `lucid`'s semantics depend on the `hashable` version, it should have bounds on `hashable` that guarantee consistent behaviour.

**Comment by sjakobi** [comment]
#103 is somewhat related.

**Comment by phadej** [comment]
No, semantics are not dependent. The order of attributes in HTML is relevant. i'm sorry that simple string equality doesn't work for you.
