### ISSUE TITLE
lucid-2.9.12.1 testsuite: attributes-with mixed failed in Nightly

### ISSUE THREAD

**Issue by juhp** [chrisdone/lucid#109]
In Stackage Nightly the testsuite failed with:

```
      test/Main.hs:43:27:                     
      1) attributes-with mixed                
           "<p class=\"foo\" style=\"attrib\"><style></style></p>" is not equal to any of ["<p style=\"attrib\" class=\"foo\"><style></style></p>","<pclass=\"foo\" style=\"attrib\"><style></style></p>"]                            
                                              
      To rerun use: --match "/attributes-with/mixed/"                                       
                                              
    Randomized with seed 1494507645                                                         
```

**Comment by chrisdone** [comment]
That's the HashMap/Hashable change of behavior causing different ordering for lucid.

It was apparently fixed in this version: https://github.com/chrisdone/lucid/issues/103#issuecomment-787119676

But perhaps this is a missed case.

**Comment by phadej** [comment]
It's not missing a case, there is genuine typo in the alternative `"<pclass=\"foo\"`. I'll fix that.

**Comment by phadej** [comment]
... accept it's already fixed: https://github.com/chrisdone/lucid/commit/242ec1748a9f1bf43d07bb37a608a7a223e830dd just not released it seems.

**Comment by chrisdone** [comment]
I've pushed 2.9.13 which fixes this.
