### ISSUE TITLE
lucid-2.9.13 violates PVP

### ISSUE THREAD

**Issue by phadej** [chrisdone/lucid#114]
The change from HashMap to Map is visible in public api (`HtmltT` constructor is public: https://hackage.haskell.org/package/lucid-2.9.13/docs/Lucid-Base.html#t:HtmlT) thus the new version should be `lucid-2.10` (or `lucid-2.10.x` or ...)

**Comment by chrisdone** [comment]
Oh, I couldn't figure out which was the breaking change number for the useless PVP. Thanks. I'll push another one to hackage.

**Comment by phadej** [comment]
> I couldn't figure out which was the breaking change number 

in https://pvp.haskell.org/ the first numbered paragraph;

> *Breaking change*. If any entity was removed, or the types of any entities or the definitions of datatypes or classes were changed, or orphan instances were added or any instances were removed, then the new `A.B` **MUST** be greater than the previous `A.B`. Note that modifying imports or depending on a newer version of another package may cause extra orphan instances to be exported and thus force a major version change.
