### ISSUE TITLE
Implement new versioning policy (immutable versioning)

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/lucid#119]
I think I'd like to apply the require/provide and name changes put together in [Spec-ulation](https://www.youtube.com/watch?v=oyLBGkS5ICk).

Essentially:

If you break a function, you make a new one e.g. foo2.
If you break a namespace, you make a new one e.g. Foo2.
If you break a package, you make a new package e.g. `lucid2`.

Where `break` means that you require more, or provide less. (Or change the meaning of something but use the same name, but that pushes the breakage one level up.)

Meanwhile, you still use minor versioning so that people can say "I want at least that thing provided to me." (as cabal can't say "I want lucid.Lucid2.map_") A date will do nicely e.g. `0.0.20211115`, as it conveys more than `0.0.3`.

It's a shame I didn't think to try applying this to the recent attributes changes, I went with the olde PVP approach. But for the next changes, I'd like to try applying this approach. Lucid is simple and doesn't change that often, so it's easy to apply.

**Comment by phadej** [comment]
Would this mean that previous changes (`HashMap` -> `Map` -> `Seq`) would resulted in `lucid2` and `lucid3` packages?

**Comment by chrisdone** [comment]
Rather, you would just make a new module hierarchy `Lucid2`. 

That way, existing users of lucid are unaffected and their test suites still pass. The one user who requested attributes in specified order update their imports to `Lucid2`.

In this example, we changed the meaning of several functions (that had `HashMap Text Text` in their signature), so the module is broken, and you make a new module. 

You would only make a new package if you provide less (i.e. remove a module) or change the meaning of a module.

What do you think?

**Comment by phadej** [comment]
I'm not excited.

**Comment by chrisdone** [comment]
Eventually, when we're tired of maintaining more than one module, we make a new package that deletes the old modules. People can continue using the old package and we'll maintain that minimally, until we're not interested in maintaining it.

> I'm not excited.

Agree, it adds a bit more work. On the other hand, downstream users will be very pleased. 

But, I don't suppose you were planning on making any breaking changes anyway, were you?

**Comment by phadej** [comment]
No, but I'm reconsidering whether I want to use `lucid` if the versioning scheme will become like that. To me new package is worse then new major version, and intermediate multimodule state won't be fun (e.g. updating the module imports).

**Comment by chrisdone** [comment]
We could just put them in the same repo as a megarepo. Why is a new package worse than a major version? 

As a user, you can do `module Lucid (module Lucid2) where import Lucid2` in your package if you don't feel like updating your imports.

In this scheme, the user pays an optional price to use new things, rather than paying a tax because the publisher removed old things. Don't you think that's better?

**Comment by phadej** [comment]
No. Let's  agree to disagree. It's your package, you can do it your way if you want.

**Comment by chrisdone** [comment]
Fair enough. :shrug:

**Comment by chrisdone** [comment]
I'll remove you as collaborator then, as your responses on this package have mostly been unhappy of late. You won't need to be bothered by this package further!

**Comment by phadej** [comment]
Thank you.
