### ISSUE TITLE
Extract attributes from `Html ()`

### ISSUE THREAD

**Issue by ajcerejeira** [chrisdone/lucid#124]
Is it possible to extract the attributes of an element after it is built? For example let's say I define:

```haskell
i = input_ [type_ "text", id_ "myID"]
```

How do I get `id` attribute from `i` element?

---

To give some context, I am trying to abstract Bootstrap inputs, by creating a function `field` that automatically includes the `label` and the `input` tag, and for that to work, `label for=` should point to the `field` `id` attribute, something like this:

```haskell
field :: Html () -> Html () -> Html ()
field label input = do
  label_ [for_ ???, class_ "form-label"] label
  input
```

```haskell
field "Name" $ input_ [type_ "text", id_ "name", class_ "form-control"]
-- <label for="name">Name</label>
-- <input type="text" id="name" class="form-control">
```

Thank you

**Comment by chrisdone** [comment]
That's not possible by lucid's design, I'm afraid.
