### ISSUE TITLE
`commuteHtmlT` is completely broken in lucid2

### ISSUE THREAD

**Issue by intolerable** [chrisdone/lucid#135]
`commuteHtmlT` in lucid2 has different semantics from `commuteHtmlT` in lucid1, and generates invalid HTML due to `HtmlT` being `State`-based rather than `Writer`-based (I think). Using the script below (which compiles and executes with both lucid1 and lucid2), the results are as follows:

lucid1: `<div class="outside-state"><div class="inside-state"></div></div>` (this I would consider "correct" behaviour)
lucid2: `<div class="inside-state"></div></div>` (?)

```haskell
#!/usr/bin/env cabal
{- cabal:
build-depends: base, text, transformers, lucid
-}
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Control.Monad.Trans.State
import Lucid
import Lucid.Base
import qualified Data.Text.Lazy.IO as Text

main :: IO ()
main = do
  Text.putStrLn $ renderText $ do
    let (content, s) = runState (commuteHtmlT stateAction) [0]
    div_ [class_ "outside-state"] $ content

stateAction :: HtmlT (State [Integer]) ()
stateAction = do
  div_ [class_ "inside-state"] $ pure ()
```

**Comment by chrisdone** [comment]
Good catch! Thanks
