### ISSUE TITLE
input elements are not closed

### ISSUE THREAD

**Issue by seanhess** [chrisdone/lucid#138]
I'm parsing lucid's output in javascript, and it's complaining because input tags aren't self-closed. Both version 1 and 2 never close input tags. For example

```
div_ $ do
  input_ [type_ "text"]

<div>
  <input type="text">
</div>
```

I would expect it to output a self-closing input tag:

```
<div>
  <input type="text"/>
</div>
```

Is this fixable?

**Comment by seanhess** [comment]
I got the spec wrong. It's the fault of the parser library.

**Comment by chrisdone** [comment]
No, that closing syntax is for XML and lucid produces HTML5. If you want to process it you might want to use an HTML parser that’ll convert to XML for you.

On Wed, Sep 21, 2022, at 10:52 PM, Sean Hess wrote:
> 
> 
> I'm parsing lucid's output in javascript, and it's complaining because input tags aren't self-closed. Both version 1 and 2 never close input tags. For example
> 
> `div_ $ do
>   input_ [type_ "text"]
> 
> <div>
>   <input type="text">
> </div>
`
> I would expect it to output a self-closing input tag:
> 
> `<div>
>   <input type="text"/>
> </div>
`
