### ISSUE TITLE
Hashable instance for Attributes

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [chrisdone/lucid#14]
Hi Chirs, 
Hope I'm not becoming a pest. I need an instance of `Hashable` for `Attribute` in
diagrams-svg, but the constructor of  `Attribute` is not exposed. Would you mind
either exposing the constructor or providing a `Hashable` instance.

thanks
jeff

**Comment by chrisdone** [comment]
I'll merge #15 in a minute.

**Comment by jeffreyrosenbluth** [comment]
thanks
