### ISSUE TITLE
Dropping the blaze-builder dependency in favour of bytestring?

### ISSUE THREAD

**Issue by Kleidukos** [chrisdone/lucid#143]
Haddock is studying the possibility of using lucid2 for HTML generation (and I've had a great experience with it on other projects). 

At present time, all the dependencies are already present in the GHC tree because they are boot libraries, except `blaze-builder`. However I'm wondering if this dependency couldn't be dropped in favour of `bytestring`'s own builder. If this was the case, `lucid2` could very easily become a dependency for haddock's HTML generator! 

What do you think? Do you reckon it's possible?

**Comment by chrisdone** [comment]
That’s a good question. I seem to recall trying to drop this dependency while making lucid2, and finding it had something that bytestring didn’t. It might be this:

https://hackage.haskell.org/package/blaze-builder-0.4.2.2/docs/Blaze-ByteString-Builder-Html-Utf8.html

But I’m not sure, don’t remember. 🤔 

I’ll look properly tomorrow when back at keyboard. On phone at the moment.

I wouldn’t be opposed to folding in a module into lucid as an unexposed other-module, if it’s relatively straightforward and would enable a lighter dependency foot print.

**Comment by chrisdone** [comment]
Indeed, I took a look and it's for the HTML encoding. I'll take a brief try at inlining that module into lucid2 and see what happens.

**Comment by chrisdone** [comment]
I did a test here: https://github.com/chrisdone/lucid/pull/144

I'd have to update the LICENSE/copyright info a little but this passes the test suite (unsurprisingly). I don't much mind adding this to the project, as it doesn't break anyone's workflow and the blaze-builder package is very stable.

If you're interested in this direction then I can probably apply the change properly (update copyright) tomorrow.

**Comment by Kleidukos** [comment]
That would be fantastic, thank you very much!! :heart: :heart:

**Comment by chrisdone** [comment]
OK, I've published [0.0.20230706](https://hackage.haskell.org/package/lucid2-0.0.20230706) which doesn't depend on blaze-builder.

**Comment by chrisdone** [comment]
Closing as this was published in July.
