### ISSUE TITLE
GHC 9.8, base-4.19 not accepted

### ISSUE THREAD

**Issue by ysangkok** [chrisdone/lucid#145]
The tests pass with just a simple bounds bump:

```
janus@janus-ux305ca /tmp/lucid-2.11.20230408
 % cabal test -w ghc-9.8.1 --allow-newer=lucid:base
Build profile: -w ghc-9.8.1 -O1
In order, the following will be built (use -v for more details):
 - lucid-2.11.20230408 (test:test) (first run)
Preprocessing test suite 'test' for lucid-2.11.20230408..
Building test suite 'test' for lucid-2.11.20230408..
Running 1 test suites...
Test suite test: RUNNING...
Test suite test: PASS
Test suite logged to:
/tmp/lucid-2.11.20230408/dist-newstyle/build/x86_64-linux/ghc-9.8.1/lucid-2.11.20230408/t/test/test/lucid-2.11.20230408-test.log
1 of 1 test suites (1 of 1 test cases) passed.
```

**Comment by chrisdone** [comment]
Oki doki. I’ll look at bumping it this weekend.

On Fri, Oct 27, 2023, at 9:17 PM, Janus Troelsen wrote:
> 
> 
> The tests pass with just a simple bounds bump:
> 
> ***@***.*** /tmp/lucid-2.11.20230408
>  % cabal test -w ghc-9.8.1 --allow-newer=lucid:base
> Build profile: -w ghc-9.8.1 -O1
> In order, the following will be built (use -v for more details):
>  - lucid-2.11.20230408 (test:test) (first run)
> Preprocessing test suite 'test' for lucid-2.11.20230408..
> Building test suite 'test' for lucid-2.11.20230408..
> Running 1 test suites...
> Test suite test: RUNNING...
> Test suite test: PASS
> Test suite logged to:
> /tmp/lucid-2.11.20230408/dist-newstyle/build/x86_64-linux/ghc-9.8.1/lucid-2.11.20230408/t/test/test/lucid-2.11.20230408-test.log
> 1 of 1 test suites (1 of 1 test cases) passed.
`

**Comment by chrisdone** [comment]
https://github.com/chrisdone/lucid/commit/5ca0fba7a9d6a96f13da966cfcb8101d8db2a366

I've bumped the upper bound to `<4.20` for both lucid and lucid2, and revised the latest versions on Hackage which includes the one you tested.

Cheers!
