### ISSUE TITLE
Lucid escapes _some_ characters but not others

### ISSUE THREAD

**Issue by gfarrell** [chrisdone/lucid#146]
MVE:

```haskell
λ: import Lucid
λ: import Lucid.Html5 
λ: "hello — world" :: Html ()
hello — world
λ: "hello — world &&&" :: Html ()
hello — world &amp;&amp;&amp;
λ: "hello — world \"&&&" :: Html ()
hello — world &quot;&amp;&amp;&amp;
```

I'd expect the em-dash to be escaped as `&mdash;`.

I'm not sure if this was an active choice or just an omission?

**Comment by chrisdone** [comment]
Lucid’s escaping is handled by the blaze-builder package, in which such decisions are made. I don’t have the authoritative answer.

However, ampersand is a reserved character in HTML by itself, whereas a variety of Unicode is not, so I see no problem with the above.

**Comment by gfarrell** [comment]
Ok, gotcha.
