### ISSUE TITLE
No dialog tag?

### ISSUE THREAD

**Issue by jacksonneal** [chrisdone/lucid#147]
I couldn't find a dialog tag.  I'd be willing to do the work to add one, just wanted to check that it was indeed missing and there was not an intent behind that.

**Comment by chrisdone** [comment]
This lib was populated from the standard at the time, dialog tag is a bit newer. Welcome to open a PR to add it!

**Comment by jacksonneal** [comment]
What is the process for publishing a new version of Lucid with that change?

**Comment by chrisdone** [comment]
Sorry, I already published it. Forgot to mention it.

**Comment by chrisdone** [comment]
https://hackage.haskell.org/package/lucid2
