### ISSUE TITLE
Streaming HTML

### ISSUE THREAD

**Issue by runeksvendsen** [chrisdone/lucid#149]
Firstly, thanks for creating this library! It's really a pleasure to use.

I'm in a situation where I'm using Lucid to generate HTML, and a portion of the HTML is inline SVG generated using GraphViz. I'm shelling out to an executable which generates the SVG for me, which I then include in my HTML via an `<svg>` tag. The problem is that running GraphViz can be quite slow, and as a consequence my server (I'm using Servant+Warp) waits sending _all_ of the HTML (even the stuff before shelling out to GraphViz) until the GraphViz IO action has returned.  
What I would like is a server that streams HTML as it is generated on the backend, so the client doesn't have to wait for all of the HTML to be generated until it sees e.g. the initial static part that takes essentially no time to generate.

Conceptually, my code looks something like this:

```haskell
page :: HtmlT IO ()
page = do
  doctype_
  html_ [lang_ "en"] $
    body_ $ do
      p_ "hello"
      expensiveComputation
  where
    expensiveComputation = do
      liftIO (threadDelay 10000000)
      p_ "world"
```

And I would like a server that sends out everything up until and including the `<p>hello</p>` almost instantly, and then sending the rest after those 10 seconds.

Is this possible?

**Comment by runeksvendsen** [comment]
Thank you for the quick reply.

> Nothing simple immediately comes to mind. Lazy I/O might get you the way there, but you'd have to be careful about chunk size, consuming lazily from the process and keeping it open, producing a streaming output for wai, etc. It's quite involved.

Sounds too cumbersome, and poorly supported by browsers (e.g. Safari has a 512 byte buffer that must be filled before content is rendered according to [this blog post](https://lamplightdev.com/blog/2024/01/10/streaming-html-out-of-order-without-javascript/)), to be viable. But I do think it's the more elegant solution. At least in combination with [the new `<slot>` element](https://lamplightdev.com/blog/2024/01/10/streaming-html-out-of-order-without-javascript/) so that the page can show a loading indicator while waiting for the remaining HTML to be streamed, and then swap that out when the final HTML arrives.  
I think it's more elegant because it allows the server to more quickly free the resource that takes a bit longer to load (it can be freed as soon as it has been streamed to the client via an already-open connection), as opposed to including an `<object>` element which means the server would need to keep the resource around until the client hits the endpoint specified by this element.

> It might be simpler to have two end-points, one for the wrapper page and one for the slow-to-create content in an `<object>` element.

I should note that my use case is slightly more complicated, roughly this:

```haskell
server queryParams = do
  result <- query queryParams -- takes 10-100 milliseconds
  graph <- createQueryGraph result -- takes seconds
  pure $ result <> graph
```

so the server needs to keep around the `result` data in order to produce the `graph` (which I, ideally, would like to stream to the client). This is why I prefer the streaming solution, in theory at least, because then I don't need to serialize `result`, send to the client, who then sends it back to my backend so that it can apply `createQueryGraph` to this data and then send the resulting `graph` to the client.

I'm also not sure that the `result` data is small enough to fit in the URL of an `object`s `data` attribute. I guess I can embed a form into the page instead, which includes the `result` data, which then POSTs this data when a button is clicked (or perhaps on page load?). But that's not quite as elegant.

**Comment by chrisdone** [comment]
I'm closing the issue as I don't think there's a lucid-specific change that comes to mind here.

I'd normally just store the job in the DB, but in your case it sounds like you're going for something quick and dirty. What about storing the query & result in the server's memory?

**Comment by runeksvendsen** [comment]
> I'm closing the issue as I don't think there's a lucid-specific change that comes to mind here.

@chrisdone thanks for clarifying. I just wanted to know if there was something obvious I was missing.

> I'd normally just store the job in the DB, but in your case it sounds like you're going for something quick and dirty. What about storing the query & result in the server's memory?

I'm not using a DB. And I want to avoid storing state on the web server in order to enable horizontal scaling. Because of that I think serializing the state and sending to the client is the best solution.
