### ISSUE TITLE
Functional dependency error with Attributes

### ISSUE THREAD

**Issue by xave** [chrisdone/lucid#152]
Working on a proof of understanding app. Been stuck on this for a while. The error is cryptic. Best to get help.

Seems something to do with a list of lists sort of situation.  Yet as far as I know I am doing things idiomatically, except for that very suspicious `htmlToString` function I made.

```
 Couldn't match type ‘Lucid.Base.Attributes’
                     with ‘lucid-2.11.20230408:Lucid.Base.Attribute’
        arising from a functional dependency between:
          constraint ‘Lucid.Base.Term
                        [lucid-2.11.20230408:Lucid.Base.Attribute]
                        (Lucid.Base.HtmlT m0 () -> Html ())’
            arising from a use of ‘li_’
          instance ‘Lucid.Base.Term
                      [Lucid.Base.Attributes] (f -> Lucid.Base.HtmlT m a)’
            at <no location info>
    • In the first argument of ‘($)’, namely ‘li_ [hxTarget_ "this"]’
      In the expression:
        li_ [hxTarget_ "this"]
          $ do button_ [hxSwap_ "outerHTML", hxDelete_ delTodoWithArg] "x"
               myListItem
      In an equation for ‘htmlRepresentation’:
          htmlRepresentation
            = li_ [hxTarget_ "this"]
                $ do button_ [hxSwap_ "outerHTML", ....] "x"
                     myListItem
    |
122 |         li_ [hxTarget_ "this"] $ do
    |         ^^^

```

Code: 

```
{-# LANGUAGE ExtendedDefaultRules #-}
{-# LANGUAGE OverloadedStrings #-}

import qualified Data.Text.Lazy as LT
import qualified Data.Text as T
import Htmx.Lucid.Core
import Htmx.Lucid.Extra
import Lucid

data TodoField = TodoField !Int64 !String deriving (Show)

todoToLi'' :: TodoField -> String
-- todoToLi'' (TodoField i s) = htmlToString htmlRepresentation
todoToLi'' (TodoField i s) = htmlToString htmlRepresentation
  where
    htmlRepresentation :: Html ()
    htmlRepresentation =
        li_ [hxTarget_ "this"] $ do
            button_ [hxSwap_ "outerHTML", hxDelete_ delTodoWithArg] "x"
            myListItem
    delTodoWithArg = "/deltodo/" <> T.pack (show i) :: T.Text
    myListItem = toHtml $ " | " <> s


htmlToString :: Html () -> String
htmlToString a = LT.unpack $ renderText a
```

It's supposed to be a Lucid version of this:

```
todoToLi :: TodoField -> String
todoToLi (TodoField i s) = printf "<li hx-target=\"this\"><button hx-swap=\"outerHTML\" hx-delete=\"/deltodo/%d\">x</button> | %s</li>" i s :: String

**Comment by xave** [comment]
Ah, hmm...

If I don't use any `htmx` stuff, it compiles. Changing everything to `id_` compiles, for instance. 

```
    htmlRepresentation =
        li_ [id_ "this"] $ do
            button_ [id_ "outerHTML", id_ delTodoWithArg] "x"
            myListItem

**Comment by xave** [comment]
This works:

```
hxGet_ :: Term arg result => arg -> result
hxGet_ = term "htmx-get"

hxTarget_ :: Term arg result => arg -> result
hxTarget_ = term "htmx-target"

hxSwap_ :: Term arg result => arg -> result
hxSwap_ = term "hx-swap"

hxDelete_ :: Term arg result => arg -> result
hxDelete_ = term "hx-delete"
```

It would be nice for there to be an `htmx` package for Lucid. There's  a few of them floating around, but they don't implement things the Lucid way, which causes breakages like this.

**Comment by xave** [comment]
I'm reopening it because there is perhaps a good opportunity to discuss the philosophy of `terms` and `attributes`. I do see that the [htmx-lucid](https://github.com/JonathanLorimer/htmx/blob/main/htmx-lucid/src/Htmx/Lucid/Extra.hs)

defines these things I had trouble with as attributes:

```
-- | <https://htmx.org/attributes/hx-delete/>
-- issues a DELETE to the specified URL
hxDelete_ :: Text -> Attributes
hxDelete_ = makeAttributes "hx-delete"
```

Yet my naive implementation says to just make everything a `term`. For my present use cases, that will certainly work. Though I am expecting that the reason for separating the two concepts in Haskell-land is for using some sort of combinators on it (like gathering all `attributes` from an `Html()`. 

Is it better to define, for instance, `hxDelete` the way I have, which got my thing to compile and generates the html I want? Or to do it as has been done with `makeAttributes`, which is, in fact, "the Lucid way".

**Comment by xave** [comment]
This is strange. When I manually defined everything using attributes, it compiled. Probably going to vendor the `htmx` definitions myself until these packages settle. I realize its all within a few months old.

**Comment by chrisdone** [comment]
I think you're using `lucid2` with a package that's build to work with `lucid` (first version).

**Comment by xave** [comment]
Thank you. I think I figured it out. Lots of packages with similar names and such. `htmx-lucid` vs `lucid-htmx` with minimal docs...
