### ISSUE TITLE
Change term indication symbol

### ISSUE THREAD

**Issue by sigrlami** [chrisdone/lucid#19]
As I see from code HTML5 terms are hard coded with postfix `_` . I want to have functionality to use terms with prefix/postfix defined by user beside standard option, something like `'body` or `body'`. 
I found it less distracting, especially with big chunks of code. I think Template Haskell will be suitable for this task. 

What is best option to achieve this?  
Is this change to code structure useful and I should submit pull request, or just keep it in my fork?

**Comment by chrisdone** [comment]
Fork. :-)
