### ISSUE TITLE
"role" attribute

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/lucid#20]
I see this used a lot in Bootstrap at least, so might be nice to have
```haskell
role_ :: Text -> Attribute
role_ = makeAttribute "role"
```
since that seems to exist for most attributes.

**Comment by HalosGhost** [comment]
It seems like this is also used for [ARIA](http://www.w3.org/TR/wai-aria/) for web accessibility. I would definitely like to see support for this!

**Comment by HalosGhost** [comment]
@chrisdone, awesome, thanks! Any chance for a new release/tag to be cut and put up on hackage?

**Comment by chrisdone** [comment]
Sure thing.

**Comment by chrisdone** [comment]
Bumped as 2.9.3.

**Comment by HalosGhost** [comment]
:+1:
