### ISSUE TITLE
MathML primitives

### ISSUE THREAD

**Issue by ggreif** [chrisdone/lucid#23]
Would you accept a contribution in the spirit of https://github.com/ggreif/leleka/blob/master/Lucid/MathML.hs?

(of course with a license corresponding to lucid...)

**Comment by chrisdone** [comment]
I think given the scope of [elements](https://developer.mozilla.org/en-US/docs/Web/MathML/Element) and [attributes](https://developer.mozilla.org/en-US/docs/Web/MathML/Attribute) a separate package, like `lucid-svg` may be in order. I intend to move `Lucid.Bootstrap` into its own package.

**Comment by ggreif** [comment]
Yeah, child packages appear like the way to go. I'll play with my little plant a bit and might come back when there is something to show.
