### ISSUE TITLE
"mixed" test fails on 32-bit platforms

### ISSUE THREAD

**Issue by dfoxfranke** [chrisdone/lucid#25]
`renderText (p_ [class_ "foo", style_ "attrib"] (do { style_ ""; style_ ""}))` can evaluate either to `<p style="attrib" class="foo"><style></style><style></style></p>`  or to `<p class="foo" style="attrib"><style></style><style></style></p>` depending on the relative hash values of `"style"` and `"class"`. The `"mixed"` test from `testAttributes` accepts only the former, but on 32-bit platforms, which use a different string hash function than 64-bit platofrms to, it gets the latter and fails. `testAttributesWith` has the same problem.

**Comment by dfoxfranke** [comment]
Looks like some other tests make similar assumptions but happen to get away with them.

**Comment by chrisdone** [comment]
No big deal, I don't dev on 32-bit platforms.

**Comment by dfoxfranke** [comment]
The test suite is strictly for your own use, then? NixOS, in general, tries to run the test suite on all Haskell libraries it packages as a safeguard against miscompilation. I had to disable the tests for `lucid` on account of this issue. Do you recommend they remain disabled indefinitely?

**Comment by dfoxfranke** [comment]
Yes, that's the patch I had in mind but I inferred from your initial response that you wouldn't be interested in taking it. Did I misinterpret?
