### ISSUE TITLE
Can the blaze-builder dep be replaced with bytestring.builder?

### ISSUE THREAD

**Issue by LukeHoersten** [chrisdone/lucid#26]
Would it be possible to drop the `blaze-builder` dependency in favor of using only `ByteString.Builder` in `bytestring`?

**Comment by chrisdone** [comment]
Currently blaze-builder's a wrapper package around bytestring-builder, so
it should be able to move to that cleanly.

**Comment by LukeHoersten** [comment]
Any reason not to do that? Would you accept a PR?

**Comment by chrisdone** [comment]
Yep I can check one out tonight.

**Comment by LukeHoersten** [comment]
We'd need a replacement for `fromHtmlEscapedString` in Blaze. I don't think `ByteString.Builder` has a directly ported function.

**Comment by LukeHoersten** [comment]
Did closing this mean it was completed?
