### ISSUE TITLE
Pretty Print HTML

### ISSUE THREAD

**Issue by seagreen** [chrisdone/lucid#28]
Is there a way to turn an `Html a` directly into a pretty printed/shown `Text`?

**Comment by chrisdone** [comment]
http://hackage.haskell.org/package/lucid-2.9.2/docs/Lucid.html

**Comment by seagreen** [comment]
Hmm, I hope I'm not missing something obvious there. Making a `Text` is easy:

```
> let html = p_ "Lorem ipsum" >> p_ "dolor sit amet" :: Html ()
> renderText html
"<p>Lorem ipsum</p><p>dolor sit amet</p>"
```

But I'd like to be able to output pretty-printed text like in the last example of the introduction: https://github.com/chrisdone/lucid#introduction, and I'm not sure how to do that.

E.g.
```
someFunc html
"<p>Lorem ipsum</p>\n<p>dolor sit amet</p>"
```
(Including the newline separating the two paragraphs)

**Comment by chrisdone** [comment]
Oh, there is no pretty printer built in.

**Comment by seagreen** [comment]
Thanks for the response!
