### ISSUE TITLE
mmorph instances

### ISSUE THREAD

**Issue by athanclark** [chrisdone/lucid#35]
It would be nice to use `HtmlT` with exceptions' mtl-style typeclass headers. I'll try to implement it myself and submit a PR.

**Comment by chrisdone** [comment]
Example?

**Comment by athanclark** [comment]
Wait nevermind :| sorry.

`lift` fixes this, but idk... mtl-style is wonderful for polluting decidable typeclass heirarchies!

**Comment by athanclark** [comment]
What about an instance for `MFunctor` from mmorph? I've got a library that encodes how urls are represented, kindof like `LoggingT` vs. `NoLoggingT` - `RelativeUrlT` and `AbsoluteUrlT`, I'd really like to do the following:

```haskell
foo :: HtmlT (AbsoluteUrlT m) ()

foo' :: HtmlT m ()
foo' = hoist (flip runAbsoluteUrlT hostname) foo
```

What do you think?

**Comment by athanclark** [comment]
It could probably fit a `MMonad`, too, where embed just appends. I'll submit a PR

**Comment by athanclark** [comment]
It looks like I can't make a `MMonad` instance, but `MFunctor` is fine.
