### ISSUE TITLE
Expose data constructor for HtmlT

### ISSUE THREAD

**Issue by andrewthad** [chrisdone/lucid#36]
I'm working with a monad transformer stack involving `HtmlT` that looks like this:

    type M = HtmlT (StateT Int Identity)

And there's a place in my code where I'd like to be able to write a function:

    seed :: Int -> M a -> Svg a

And I can't write this if I don't have access to the data constructor. One obvious solution would be to flip the ordering of the stack like so:

    type M = StateT Int (HtmlT Identity)

But lucid doesn't have an mtl-style interface so I would need to call `lift` almost everywhere since `HtmlT` is the monad transformer I use way more often. (Note: I'm totally fine with the lack of an mtl-style typeclass. I don't even like using mtl to begin with.)

**Comment by chrisdone** [comment]
I can expose it (nothing against it particularly) but if I understand the problem, you just want to get the underlying transformed `StateT Int Identity` from the `HtmlT`, if that's true then that is available via [the accessor function `runHtmlT`](http://hackage.haskell.org/package/lucid-2.9.3/docs/Lucid.html#v:runHtmlT):

``` haskell
-- | A monad transformer that generates HTML. Use the simpler 'Html'
-- type if you don't want to transform over some other monad.
newtype HtmlT m a =
  HtmlT {runHtmlT :: m (HashMap Text Text -> Builder,a)
         -- ^ This is the low-level way to run the HTML transformer,
         -- finally returning an element builder and a value. You can
         -- pass 'mempty' for this argument for a top-level call. See
         -- 'evalHtmlT' and 'execHtmlT' for easier to use functions.
         }
```

**Comment by andrewthad** [comment]
Almost. I'll try to explain my need a little better. I want to be able to rip out than inner monad and apply it, but still end up with an `HtmlT`. `runHtmlT` almost gets me there, but then I have a `State Int (HashMap Text Text -> Builder, a)`, and I can do the usual `evalState` to get a `(HashMap Text Text -> Builder, a)`, but then I then I can't turn that back into `Html`, although the data constructor trivially does just that.

**Comment by chrisdone** [comment]
Ah, I'd hoped you didn't need to rebuild the HtmlT. Fair enough, I'll expose it post-haste.

**Comment by andrewthad** [comment]
Thanks. It's not urgent though, so take your time.

**Comment by chrisdone** [comment]
Okay, pushed lucid-2.9.4 which exposes this constructor.

**Comment by andrewthad** [comment]
Cool. Thanks so much!

**Comment by ocharles** [comment]
(I think this can be closed now then)
