### ISSUE TITLE
how to <html ng-app>

### ISSUE THREAD

**Issue by Heather** [chrisdone/lucid#41]
How can I use `<html ng-app>` except `toHtmlRaw`

**Comment by chrisdone** [comment]
You can define one:

``` haskell
-- | The @ng-app@ attribute.
ngapp_ :: Attribute
ngapp_ = makeAttribute "ng-app" ""
```

``` haskell
html_ [ngapp_] (body_ (p_ "Hi!"))
```

`<html ng-app="">` is semantically equivalent to `<html ng-app>`

> Certain attributes may be specified by providing just the attribute name, with no value.
> 
> In the following example, the disabled attribute is given with the empty attribute syntax:
>
>     <input disabled>
> 
> Note that empty attribute syntax is exactly equivalent to specifying the empty string as the value for the attribute, as in the following example.
> 
>     <input disabled="">

**Comment by Heather** [comment]
@chrisdone thanks :+1:
