### ISSUE TITLE
Identity instance for ToHtml?

### ISSUE THREAD

**Issue by ocharles** [chrisdone/lucid#42]
What do you think about an identity instance for ToHtml?

``` haskell
instance a ~ () => ToHtml (HtmlT m a) where
  toHtml = id
  toHtmlRaw = id
```

This is useful in the scenario that you have a function that is polymorphic over anything that is `ToHtml`, but when you end up in the situtation that you want to call this function on data where there _isn't_ an instance available (and defining it is impossible without orphan instances) - the only option is to have the user cast `ToHtml` and then having the function use the `toHtml = id` implementation.

**Comment by chrisdone** [comment]
Sure, why not. Don't see any negative consequence.

**Comment by phadej** [comment]
I'll add 

```hs
instance (a ~ (), m ~ Identity) => ToHtml (HtmlT m a) where
  toHtml = relaxHtmlT
  toHtmlRaw = relaxHtmlT
```

**Comment by phadej** [comment]
In http://hackage.haskell.org/package/lucid-2.9.8
