### ISSUE TITLE
Does textarea_ have to take an argument?

### ISSUE THREAD

**Issue by neongreen** [chrisdone/lucid#45]
I can write `textarea_ [] ""`, but I can't write `textarea_ []` or `textarea_`. Is it possible for `textarea_` not to require an argument?

**Comment by NerdGGuy** [comment]
Currently I don't believe that's possible. But I believe `textarea_ ""` or `textarea_ mempty` should work.

**Comment by phadej** [comment]
`textarea_ mempty` is the best what we can have. There have to be some argument.

**Comment by phadej** [comment]
I'll close this, I don't have a simple solution to this anyway.
