### ISSUE TITLE
Change `class_` type

### ISSUE THREAD

**Issue by mizunashi-mana** [chrisdone/lucid#50]
Now, the type of `Lucid.Base.class_` is `Text -> Attribute`.
However, class attribute is used with multiple params usually.

I suggest to change the type of `Lucid.Base.class_` to `[Text] -> Attribute` and the logic to such as:

``` haskell
class_ :: [Data.Text.Text] -> Attribute
class_ cs = makeAttribute "class" $ Data.Text.intercalate " " cs
```

**Comment by NerdGGuy** [comment]
It's true that this would be useful since I sometimes do this internally:

    div_ [class_ $ T.unwords ("line":messageClasses) ] $ do

That being said in my current project I have 64 uses of class_ and 62 of them are static and would not benefit from a list. I think the proposal would be to make an array valid for certain attributes. This might work for style_ as well.

    class_ :: SpaceDelimitedValues a => a -> Attribute
    style_ :: SemicolonDelimitedValues a => a -> Attribute

**Comment by mizunashi-mana** [comment]
I think it is difficult to apply this request to style attribute (https://www.w3.org/TR/2001/WD-css-style-attr-20010305).
Perhaps, we should change just class attribute.

I resuggest add `classL_` such as:
```haskell
classL_ = makeAttribute "class" . T.unwords
```

I think `SpaceDelimitedValues` is incompatible with `OverloadedStrings`.

**Comment by chrisdone** [comment]
Perhaps `classes_`?

**Comment by mizunashi-mana** [comment]
@chrisdone yeah.  `classL_` is more easily to type for me.  But, `classes_` is also ok.

any suggestions from others?

**Comment by 3noch** [comment]
I often end up writing `classes` in my own code bases so 👍 from me.
