### ISSUE TITLE
xhtml ?

### ISSUE THREAD

**Issue by reuleaux** [chrisdone/lucid#54]
I have tried to use lucid for creating xhtml (html5 + xhtml ie.),
use `<br/>` instead of `<br>` eg.,

`<img.../>` instead of `<img ...>` ,
`<link>...</link>`

so far my approach was to introduce new tags myself:

```haskell
closingLink_ :: Term arg result => arg -> result
closingLink_ = term "link"

xmlBr_ :: Monad m => [Attribute] -> HtmlT m ()
xmlBr_ = with (makeXmlElementNoEnd "br")

xmlHr_ :: Monad m => [Attribute] -> HtmlT m ()
xmlHr_ = with (makeXmlElementNoEnd "hr")

-- and then in my pages:

closingLink_ [rel_ "stylesheet",type_ "text/css",href_ "screen.css"] ""

xmlBr_ []

xmlHr_ []
```

I would have thought that this is a more common thing to do
(xhtml can still be used even in the age of html5, and one may
argue that it is a good thing to do so)

obviously it's kind of tiresome to introduce all these
xhtml tags by hand, would it be possible 

* to either have them predefined (next to the existing tags br_, img_):
  don't know what would be good names for them: xbr_, ximg_ maybe ?

* or to just use the the existing tags: br_, img_ etc
  and have a different renderer take care of producing xhtml ?

Thanks in advance.

**Comment by chrisdone** [comment]
Lucid is specifically for HTML5. I don't intend to support XHTML in any form. Sorry! 🙈 

You could define a wrapper library that re-exports everything except hr, br, etc. and export your own versions, and your own doctype. I'm not sure that the encoding of entities is the same for HTML5 as it is in XHTML, or the use of many elements and attributes. But that's your challenge! 😉

**Comment by reuleaux** [comment]
Ok, thanks a lot.
