### ISSUE TITLE
Doc clarification for new starters

### ISSUE THREAD

**Issue by osfameron** [chrisdone/lucid#57]
I found the docs at https://hackage.haskell.org/package/lucid-2.9.6/docs/Lucid.html difficult (well, impossible) to follow, due to eliding some things that are probably clear to an experienced Haskeller but non-obvious otherwise.  I think it's just the following 3 lines, without which the examples provided won't run in ghci:

```
:import Lucid
:import Data.Monoid ((<>))
:set -XOverloadedStrings
```

(I realise that OverloadedStrings *is* mentioned, but the current phrasing "is written" doesn't make it explicit that you have to *do* something in order for them to be written like that...)

If that kind of change is something that would be generally welcome, I'm happy to draft a PR if that'd be helpful.

**Comment by chrisdone** [comment]
Fixed in https://github.com/chrisdone/lucid/commit/39cb29f6ef910931b62625914877c0992b6251bb

**Comment by HakimCassimallyBBC** [comment]
Thanks for such a quick response, the new wording looks great.
