### ISSUE TITLE
Better way to implement conditional attributes?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#59]
I'm wondering if there is better/shorter way to get the conditional `checked_` attribute:

```
    makeCheckbox label name value = with div_ [class_ "checkbox"] $ label_ $ do
      input_ $ [type_ "checkbox", name_ name] ++ (if value then [checked_] else [])
      (toHtml label)
```

**Comment by chrisdone** [comment]
Perhaps `[type_ "checkbox", name_ name] ++ [checked_ | value]`?

**Comment by saurabhnanda** [comment]
Where is `|` coming from? I checked on stackage - https://www.stackage.org/lts-7.14/hoogle?q=%7C

**Comment by ggreif** [comment]
@saurabhnanda it is the _boolean guard syntax_ for list comprehensions.

**Comment by saurabhnanda** [comment]
Hmm... somehow this seems to hacky to me! This is the first time I'm seeing list comprehensions being used in the wild.

**Comment by 3noch** [comment]
@saurabhnanda Haha...list comprehensions aren't commonly used this way. But it's a neat trick in this context. \

**Comment by chrisdone** [comment]
I don't think a satisfactory technical answer is definable here.

**Comment by saurabhnanda** [comment]
Would it be possible to change the API in favour of developer UX? I suspect a **lot** of use-cases would fit into the following structure:

```
input_ [type_ "checkbox", checked_ boolValue]
```

**Comment by 3noch** [comment]
@saurabhnanda I think the goal of Lucid's API is to exactly mimic HTML. But what you've described *is* a good idea and I commonly use it myself. Perhaps another issue is in order to recommend an *additional* API that provides those conveniences.
