### ISSUE TITLE
Better way to implement conditional HTML tags?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#60]
Here's what I was trying to do. Depending on whether `row ^. R.clientDomain` evaluated to `Maybe x` or `Nothing` include or exclude the `small_` tag from the HTML output. 

Here's the best that I could do, and I'm still looking for a shorter way to get this done. (Btw, this solution isn't even 100% correct. If `row ^. clientDomain` is `Nothing` this still includes an empty `<small></small>` tag in the HTML)

```
instance (ToHtml a) => ToHtml (Maybe a) where
  toHtml (Just x) = toHtml x
  toHtml Nothing = mempty

  with td_ [class_ "client-name"] $ do
    div_ (toHtml $ row ^. R.clientName)

    -- TODO: this shouldn't be there if the domain is NULL
    small_ (toHtml $ row ^. R.clientDomain)
```

**Comment by saurabhnanda** [comment]
Any help here? Is the question ambiguous - should I clarify it further?

**Comment by chrisdone** [comment]
Use `mapM_`:
```haskell
> :t mapM_
mapM_ :: (Monad m, Foldable t) => (a -> m b) -> t a -> m ()
```
Lists and `Maybe` are instances of `Foldable`.

```haskell
> newtype Domain = Domain Text deriving (ToHtml)
> let clientDomain = Just (Domain "org.potato")
> let clientDomainEmpty = Nothing :: Maybe Domain
> mapM_ (small_ . toHtml) clientDomain :: Html ()
<small>org.potato</small>
> mapM_ (small_ . toHtml) clientDomainEmpty :: Html ()
```
