### ISSUE TITLE
Possible to derive ToHtml for newtypes on Text?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#61]
I have quite a few newtypes in my core app for greater type safety, eg:

```
newtype Tag = Tag T.Text deriving (Show, Eq, Ord)
```

For the purpose of `ToHtml` it would be alright to treat them at-part with `Text`. Is it possible to auto-derive a boilerplate `ToHtml` instance for such cases?

**Comment by chrisdone** [comment]
You can put `ToHtml` in your `deriving` list, sure! GHC will tell you to enable `GeneralizedNewTypeDeriving` and you're good to go.

**Comment by saurabhnanda** [comment]
> You can put ToHtml in your deriving list, sure! GHC will tell you to enable GeneralizedNewTypeDeriving and you're good to go.

You're right. GHC told me to do that, but is it safe to do it? I'm afraid all this Generic stuff is black magic to me, right now.

**Comment by chrisdone** [comment]
It's a bog standard extension.
