### ISSUE TITLE
How to emit raw HTML entities?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#62]
How do I make this work so that it emits `&times;` and not `&amp;times;`?

```
with button_ [class_ "close", data_ "dismiss" "modal"] $ span_ "&times;"
```

**Comment by chrisdone** [comment]
Use `toHtmlRaw`. You could just use the proper unicode character though.

**Comment by saurabhnanda** [comment]
@chrisdone the following didn't compile:

```
with button_ [class_ "close", data_ "dismiss" "modal"] $ span_ $ toHtmlRaw "&times;"
```

whereas the following did:

```
with button_ [class_ "close", data_ "dismiss" "modal"] $ span_ $ toHtmlRaw ("&times;" :: T.Text)
```

Why the need for the extra type annotation?

**Comment by ggreif** [comment]
[`-XNoMonomorphismRestriction`](http://stackoverflow.com/questions/4575040/what-is-xnomonomorphismrestriction) might help.

**Comment by chrisdone** [comment]
`-XExtendedDefaultRules` may work better. `toHtmlRaw` is overloaded, and you passed it an overloaded string. So there's no way to determine that you meant Text.

**Comment by saurabhnanda** [comment]
[rant]

@chrisdone @ggreif what would be a good place to complain loudly about this? I thought type-inference was a headline feature in Haskell! Btw, functions dealing with html construction also don't compile without an explicit type annotation.

**Comment by chrisdone** [comment]
The following works:

```haskell
{-# LANGUAGE OverloadedStrings, ExtendedDefaultRules #-}
import Lucid
x :: Html ()
x = span_ (toHtmlRaw "&nbsp;")
```

Lucid uses a lot of non-Haskell 2010 overloading to achieve its simplicity of writing. So that's why sometimes inference gets stuck. You can use `ExtendedDefaultRules` so that `"foo"` `OverloadedStrings` will default to `String` if it's ambiguous, much like how `1` defaults to `Integer` if its type can't be inferred.
