### ISSUE TITLE
Performance issues with HtmlT over IO?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#63]
I started noticing some severe performance drop when combining Scotty's `ActionT` with Lucid's `HtmlT`. A little benchmarking produced the following: https://github.com/vacationlabs/monad-transformer-benchmark which seems to suggest that the underlying problem may be with `HtmlT IO a`, which takes more than 2x the time required for `HtmlT Reader` or `HtmlT Identity`

```
benchmarking renderText
time                 32.04 ms   (31.14 ms .. 32.54 ms)
                     0.997 R²   (0.994 R² .. 1.000 R²)
mean                 31.73 ms   (31.25 ms .. 32.21 ms)
std dev              1.049 ms   (785.1 μs .. 1.321 ms)
variance introduced by outliers: 11% (moderately inflated)

benchmarking renderTextT Identity
time                 31.37 ms   (30.17 ms .. 32.47 ms)
                     0.995 R²   (0.989 R² .. 0.998 R²)
mean                 32.90 ms   (32.23 ms .. 33.53 ms)
std dev              1.359 ms   (1.064 ms .. 1.839 ms)
variance introduced by outliers: 11% (moderately inflated)

benchmarking renderTextT Reader
time                 33.45 ms   (32.94 ms .. 33.94 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 34.38 ms   (33.95 ms .. 35.18 ms)
std dev              1.177 ms   (647.7 μs .. 1.982 ms)
variance introduced by outliers: 11% (moderately inflated)

benchmarking renderTextT IO
time                 74.52 ms   (73.08 ms .. 75.69 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 75.17 ms   (74.51 ms .. 76.00 ms)
std dev              1.247 ms   (880.2 μs .. 1.742 ms)
```

Haskell-cafe discussion: https://mail.haskell.org/pipermail/haskell-cafe/2017-January/126141.html
Reddit discussion: https://www.reddit.com/r/haskell/comments/5qpi15/expected_performance_drop_while_using_monad/

**Comment by 3noch** [comment]
I'm very interested in this as well as I tend to use Lucid a lot.

**Comment by phadej** [comment]
I pushed a branch https://github.com/chrisdone/lucid/tree/bench if someone is interested in seeing what happens. I get similar results, IO takes 2x time of pure variant.

**Comment by saurabhnanda** [comment]
There was a lot of discussion about this on the haskell-cafe mailing list. There's a possible solution at https://mail.haskell.org/pipermail/haskell-cafe/2017-January/126151.html which is mainly about using INLINE pragmas. Is there any downside to this approach?

**Comment by phadej** [comment]
Released as http://hackage.haskell.org/package/lucid-2.9.8.1
