### ISSUE TITLE
Expose monadic state in ToHtml class

### ISSUE THREAD

**Issue by athanclark** [chrisdone/lucid#73]
Hey there,

I've found myself leveraging `HtmlT` quite often for its monadic state - I'll encode some crazy constraints in `m` like `MonadBaseControl IO`, so I can perform application-related effects when I render a view, where the read-only state _of that view_ is represented by a data type which implements this typeclass.

I'm wondering if the exposure of the `m` type variable could help with effect-stack specific rendering instances, rather than forcing a view to be pure:

```haskell
toHtml :: (ToHtml a, Monad m) => a -> HtmlT m ()
```

would become

```haskell
toHtml :: (ToHtml m a, Monad m) => a -> HtmlT m ()
```

and instances, originally looking like

```haskell
instance ToHtml State where
  toHtml State{foo,bar} = do
    p_ "something forcibly pure, due to this html working forall m"
```

could become

```haskell
data Env = Env
  {hostname :: String, databaseQuery :: Query -> IO [Result], ...}

type AppM = ReaderT Env IO

instance ToHtml AppM State where
  toHtml State{foo,bar} = do
    Env{hostname,databaseQuery,etc} <- lift ask
    p_ $ "The hostname: " <> T.pack hostname
```

Personally I think this would be a major advantage for server-side rendering, as it could model something similar to Elm or Thermite.

**Comment by phadej** [comment]
If there isn't type-inference problems, than I don't see a problem why not.

The pure elements could be

```
class Monad m => ToHtml m a where
    toHtml :: a -> HtmlT m ()

instance Monad  m => ToHtml m Int where
    toHtml = toHtml . show

**Comment by athanclark** [comment]
it would have the same level of generality over monads as mtl, so I think it should be fine, given that people don't write something like `instance MonadApp m => ToHtml m Foo where`, but even then I think most users should be fine.

**Comment by athanclark** [comment]
We can expose quite a lot of kit for casual types, like `Maybe`, lists and tuples, but exposing the `m` for the typeclass is intended for _users_ - that way they can specify a more restrictive monad which gives them application-specific facilities in their rendering process, while instances from the standard library would just casually use pure `Monad m =>` instances, because they shouldn't fire missiles.

**Comment by phadej** [comment]
If we go for this, I'd like to be able to write in the application code:

```haskell
instance  (HasSomeThing r, MonadReader r m) => ToHtml Foo where
    toHtml (Foo foo) = do
        someThing <- asks someThing
        b_ $ toHtml foo <> toHtml someThing 
```

**Comment by athanclark** [comment]
Given that `HtmlT` has an inductive MonadReader instance, you should be fine - it would just be `ToHtml m Foo`

**Comment by athanclark** [comment]
I think that this messes with how Term is solved though

**Comment by chrisdone** [comment]
Did you go ahead with this in the end? Should we close this?

**Comment by athanclark** [comment]
Hey @chrisdone, yes I've forked it and implemented the monadic doodad. I'll file a PR right now.
