### ISSUE TITLE
How to write helper functions that generate "wrapping" HTML?

### ISSUE THREAD

**Issue by saurabhnanda** [chrisdone/lucid#79]
I'm trying to do something like..

```
container_ :: Term arg result => arg -> result
container_ arg = table_ [align_ "center", class_ " container "] $ do
  tbody_ $ do
    tr_ $ do
      td_ arg
```

... which can be used like:

```
div_ $ do
  container_ $ do
    strong_ "wil this work"
  container_ [class_ "extra-classes"] $ do
    strong_ "what about this?
```

... but I can't get the definition of `container_` to type-check. The best that I could get to compile is:

```
container_ :: (Monad m) => HtmlT m () -> HtmlT m ()
container_ arg = table_ [align_ "center", class_ " container "] $ do
  tbody_ $ do
    tr_ $ do
      td_ arg
```

**Comment by saurabhnanda** [comment]
The problem with what I've gotten to work is that I can't add extra attributes in the call-site, i.e. the following does not work...

```
foo :: Html ()
foo = do
  container_ [class_ "something else"] "doe sthis work"
  container_ "what about this?"
```

.. with the following definition of `container_`:

```
container_ :: (Monad m) => HtmlT m () -> HtmlT m ()
container_ arg = table_ [align_ "center", class_ " container "] $ do
  tbody_ $ do
    tr_ $ do
      td_ arg
```

**Comment by chrisdone** [comment]
Use the `with` combinator to attach attributes to an element: 

``` 
> with container_ [class_ "foo"] $ p_ "woo!" :: Html ()
<table class=" container foo"><tbody><tr><td><p>woo!</p></td></tr></tbody></table>
```

**Comment by saurabhnanda** [comment]
Thanks. However, if one wanted to have the ability to compose `container_` with/without attributes (like how `p_` or `div_` is done), how would one do it?

Also, if I have the following DSL:

```
row_ $ do
  column_ "blah"
  column_ "blah"
  column_ "blah"
```

...is there any way to automagically inject an additional attribute in the first/last `column_`?

**Comment by 3noch** [comment]
Most likely you'd just create another monad transformer that allows you to modify the HTML on the way to HtmlT

**Comment by chrisdone** [comment]
That's the options. Use `with` or just make attributes an argument to your `container_` function. There isn't a way to overload custom elements.
