### ISSUE TITLE
Using multiple class_ attributes combines them incorrectly

### ISSUE THREAD

**Issue by mpickering** [chrisdone/lucid#84]
I have some code which looks like..

```
[class_ "blc", class_ (select correct)]
```

this then generates HTML which looks like

```
<td class="correctblc">B</td>
```

Is there a way to combine attributes without concatenating strings?

**Comment by phadej** [comment]
Good question. I was avoiding searching for an answer. 

To put differently, do you think there are attributes where concatenating with a space in between would be wrong thing to do?

**Comment by mpickering** [comment]
I'm not an HTML expert but it seems that concatenating without a space is *definitely* the wrong thing to do. Concatenating with a space might sometimes be incorrect but more likely to be so than the current behaviour.

**Comment by chrisdone** [comment]
This is the documented behavior of attribute combining. It uses a simple monoidal append on the `Text`. We don't attach any semantic meaning to the attribute value. 

Other options might be: wrapping values you give to `class_` with spaces, or having the `class_` function itself wrap spaces around your input.

**Comment by phadej** [comment]
@chrisdone I'm *speculating* that we should use 

```haskell
"" <+> x  = x
x  <+> "" = x
x  <+> y  = x <> " " <> y
```

`Monoid`.

I cannot think where it could broke things; but I'm not sure.

**Comment by chrisdone** [comment]
I think that semantic only applies to `class_`, which is why either the `class_` function should insert such spaces or users of it should. Other attributes `id`, `data-`, etc. don't carry "space-separated" semantics.

**Comment by phadej** [comment]
They don't. Yet

```haskell
div_ [ id_ "foo", id_ "bar" ]
```

is non-sense. 

---

One more alternative is to have (a special module with)

```haskell
class_ = makeAttribute "class" . (<> " ")
style_ = makeAttribute "style" . (<> ";")
```

these will compose well with `<>`; but produce not-the-prettiest HTML

**Comment by chrisdone** [comment]
Indeed. There's a lot of ugly floating around this design space. I'm not particularly against just making the existing `class_ "foo"` output `" foo "`. Let's face it `class_` and `style_` are the only things I can think of that one one ever combine. Aside from maybe `data-`, but the rules to combine that would be user-specified anyway.  That way we keep a predictable instance.

**Comment by ocharles** [comment]
@chrisdone You seemed in favor of this, but then it got closed a year later. Would you accept a PR that space-separated attributes? I also find the current behavior frustrating, as when using Tailwind CSS it's nice to be able to factor out common class sets, like `outline = class_ "outline outline-0 focus:outline-4 outline-indigo-200"`

**Comment by chrisdone** [comment]
I'm up for it.

@ocharles How do you feel about importing a module called `Lucid2` which would expose this change? :)

**Comment by ocharles** [comment]
I don't really like https://gist.github.com/chrisdone/f71a2eca728a805c181091863c339fc2, but if that's what you want to do then I can try and do that.

**Comment by chrisdone** [comment]
I don't mind doing the change--it's pretty easy--as long as it's actually useful.

* I can either:
  * clone the `Lucid.Html5` module with the change, 
  * clone `Lucid`, 
  * or clone the package `lucid`.
* Another option is to add another combinator e.g. `classes_` and `_styles_` that would add spaces around. (At the risk of accidentally using the old names.)

**Comment by ocharles** [comment]
To throw another suggestion in (though this might not be easily doable) - in Elm there is both `class :: String` and `classList :: [(String, Bool)]`. This is quite nice for toggling classes. I guess if you want to work strictly under a monoid `Map Text (First Bool)` is probably more accurate.

Out of your options, I would probably prefer any of the first options, because accidentally using `class_` is just going to annoy me.

**Comment by chrisdone** [comment]
Right, a `classList_ :: [(String, Bool)]` sounds good as a direction, I've wanted something like that before. Before getting into feasibility, would that be an orthogonal feature, or would it also solve your current problem?

**Comment by ocharles** [comment]
I think it would solve my problem. It'd be a tiny bit weird, as I'd be doing something like:

```haskell
outline = classList_ $ [ "outline", "outline-0", "focus:outline-4" ] <&> (, True)
```

but I can live with that. I will have to condition myself to use `classList_`. I guess there's also a problem of what does

```haskell
class_ "foo", classList [("bar", True)]
```

mean? I would _expect_ `foo bar`, but I imagine we could also end up back at `foobar`.

**Comment by chrisdone** [comment]
Right, we come back to `class_`. Elm does the right thing and inserts a space between those, I tested it. Thanks for pointing out that case.

Then I can try the `Lucid2` approach then.

**Comment by chrisdone** [comment]
@ocharles How's this? https://github.com/chrisdone/lucid/pull/126
