### ISSUE TITLE
Update to HTML5.2

### ISSUE THREAD

**Issue by phadej** [chrisdone/lucid#85]
HTML5.2 is now a *W3C Recommendation* (14 December 2017), therefore it would
be good idea to update `Html5` module to include things in the spec.

I suggest to add both spec, and MDN links as follows, so `lucid` haddocks
could act as a good summary of what's in HTML5.2:

```haskell
-- | The @poster@ attribute
-- [W3C REC](https://www.w3.org/TR/html5/semantics-embedded-content.html#element-attrdef-video-poster)
-- [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-poster)
poster_ :: Text -> Attribute
poster_ = mkAttribute "poster
```

[HTML5.2 Changes](https://www.w3.org/TR/html5/changes.html#changes) and
[HTML5.1 Changes](https://www.w3.org/TR/html51/changes.html#changes) would
help to spot missing things. However, I'd prefer a complete spec scan anyway.

**Comment by chrisdone** [comment]
I'm not personally interested in these new attributes or implementing it, so I'm assigning to you to aid issue filtering.

**Comment by chrisdone** [comment]
I'm fine with people adding attributes on a per need basis. I don't think anyone's going to do this task.
