### ISSUE TITLE
Refactor to provide MonadHtml

### ISSUE THREAD

**Issue by mordae** [chrisdone/lucid#93]
I believe that having a `MonadHtml` analogous to `MonadReader` would make it possible to create neat single-purpose HTML widgets with controlled access to the application data model (without direct access to IO, for example).

Is such a large API change worth considering or would it be better to create a fork?

**Comment by phadej** [comment]
In short, believe me, it won't work.

`IsString` instance and back-reasoning and `MonadHtml` won't work.

---

What you **can** do, is to use

```haskell
myWidget :: MonadFoo m => HtmlT m ()
myWidget = ...
```

**Comment by mordae** [comment]
OK.
