### ISSUE TITLE
Define MonadFix for HtmlT

### ISSUE THREAD

**Issue by enobayram** [chrisdone/lucid#95]
Would you be interested in defining the `MonadFix` instance for `HtmlT`? It could be useful for creating a table of contents, among other things:

```
body_ $ mdo
  h1_ "Table of Contents"
  forM sections $ \(sectionName, sectionId) -> a_ [href_ $ "#" <> sectionId] $ toHtml sectionName
  sections <- forM sectionData $ ... return (sectionName, sectionId)
```

**Comment by phadej** [comment]
If it's lawful instance, there is no reason not to have one.

**Comment by enobayram** [comment]
@phadej Well, `HtmlT` is just a `WriterT`, isn't it? [`WriterT` seems to have a `MonadFix` instance](http://hackage.haskell.org/package/mtl-2.2.2/docs/Control-Monad-Writer-Lazy.html#t:WriterT).

**Comment by phadej** [comment]
@enobayram if you are sure it can be implemented, make a PR (add your example as a test).
