### ISSUE TITLE
Tests on `Html ()`

### ISSUE THREAD

**Issue by german1608** [chrisdone/lucid#99]
Hi there! Thanks for the work on this repo, it's neat!

I'd like to test the `Html ()` generation of my project  `dhall-docs` (https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-docs), and a way to do so is writing some golden tests.

The issue is that currently all the output is in a single line and it would be handy to pretty-print it so I can know what is the actual difference when a test fails, not the whole single line.

I know that the package does not provide a way to pretty-print `Html ()`, so I'd like to know:

1. Do you recommend another way to test the `Html ()` generation?
1. Are you open to PRs? I think that after finishing my work at `dhall-docs` I may have time to try and add that function, that may be handy to future devs.

**Comment by chrisdone** [comment]
I won’t merge pretty printing into the package; you can’t add printing from the inside without an overhaul, therefore any pretty printing will require some tokenizing and reprinting. Given this, a pretty printer can be written in isolation. Pretty printers aren’t easy to do well and are effort sinks in terms of configurations, so I would push that burden onto someone else.

I’m sure you could actually find on hackage a number of HTML packages with pretty printers.

Don’t forget that hspec uses colors to show the diff between expected and actual if you pass --colors.

**Comment by german1608** [comment]
I understand chris. Thanks for your response. I'll close this issue then.
